spring:
  profiles:
<<<<<<< HEAD
    active:
      - dev
---
#端口号
server:
  port: 8001
eureka:
  #服务注册
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
spring:
  #服务名称
  application:
    name: PLAT-PROVIDER
  profiles: dev #开发环境

---
#端口号
server:
  port: 8002
=======
    active: dev
---
server:
  port: 8001
spring:
  application:
    name: COMMIT-SERVICE
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: 123456
  profiles: dev
>>>>>>> ca6bbc138736bf6afd6cc442a2b0ab2995701ef1
eureka:
  #服务注册
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://localhost:7001/eureka
=======
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:myjava/aigou/mapper/*Mapper.xml
  type-aliases-package: itsource.aigou.domain
---
server:
  port: 8002
>>>>>>> ca6bbc138736bf6afd6cc442a2b0ab2995701ef1
spring:
  #服务名称
  application:
<<<<<<< HEAD
    name: PLAT-PROVIDER-TEST
profiles: test #开发环境
=======
    name: COMMIT-SERVICE-TEST
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou_test
      username: root
      password: 123456
profiles: test
>>>>>>> ca6bbc138736bf6afd6cc442a2b0ab2995701ef1
