spring:
  profiles:
    active: dev
---
server:
  port: 8888
  max-http-header-size: 4048576
spring:
  application:
    name: REDIS-PRIVODER
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8848
  max-http-header-size: 4048576
spring:
  application:
    name: REDIS-PRIVODER-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

