spring:
  profiles:
    active: dev

---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  prefix: "/aigou"
  ignored-services: "*"
  routes:
    plat.serviceId: plat-provider
    plat.path: /plat/**
    product.serviceId: product-service
    product.path: /product/**

---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9528.com
    prefer-ip-address: true
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  prefix: "/aigou"
  ignored-services: "*"
  routes:
    plat.serviceId: plat-provider
    plat.path: /plat/**
    product.serviceId: product-service
    product.path: /product/**